# Generated by Django 4.1.6 on 2023-02-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите имя товара', max_length=50, verbose_name='Название')),
                ('description', models.TextField(help_text='Введите описание товара', max_length=250, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(help_text='Укажите цену товара', verbose_name='Цена в центах')),
            ],
        ),
    ]
