# Generated by Django 4.1.6 on 2023-02-17 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='country',
            field=models.TextField(default='USA', help_text='Введите страну валюты', max_length=168, verbose_name='Страна валюты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='name',
            field=models.CharField(default='USA', help_text='Укажите название валюты', max_length=50, verbose_name='Валюта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='items.item'),
        ),
    ]
