# Generated by Django 4.1.6 on 2023-02-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_item_currency_delete_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USA', '$')], help_text='Выберите валюту', max_length=50, verbose_name='Валюта'),
        ),
    ]
