# Generated by Django 4.1.6 on 2023-02-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_item_currency_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', '$'), ('eur', '€')], help_text='Выберите валюту', max_length=50, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(help_text='Введите описание товара', max_length=300, verbose_name='Описание'),
        ),
    ]
